### ISSUE TITLE
Releasing training code

### ISSUE THREAD

**Issue by P0lyFish** [megvii-research/NAFNet#12]
Hi,
Thank you for your impressive work. Are you going to publish your training code? If yes, when will they be available?

**Comment by mayorx** [comment]
Hi, P0lyFish,

Thanks. The training code has been released, you can check the instruction for each task https://github.com/megvii-research/NAFNet#image-restoration-tasks.

**Comment by P0lyFish** [comment]
Thanks for your reply. I suggest changing the name of the section since it is a little bit confusing. I will close this issue.

**Comment by mayorx** [comment]
Thanks for your suggestion, updated!
