### ISSUE TITLE
Inference/Quick start for stereo image super_resolution

### ISSUE THREAD

**Issue by hamzakhalil798** [megvii-research/NAFNet#14]
Kindly add script for single image  stereo image super-resolution task aswell.
currently, it has scripts for only image denoising and image deblurring.

![inf](https://user-images.githubusercontent.com/103629235/165296971-71f7c2e2-14bb-4a6f-9da2-1cedd9bc224a.PNG)

**Comment by achusky** [comment]
Hi, hamzakhalil798

We add demo script for stereo image super-resolution (SR) task now. Please check latest README.
Our NAFSSR is designed for Stereo SR which requires two input images (i.e., left view and right view). 
You can also load two identical images for single image super resolution.

**Comment by hamzakhalil798** [comment]
Thankyou @achusky
