### ISSUE TITLE
Need help with custom datasets

### ISSUE THREAD

**Issue by renxiangdai** [megvii-research/NAFNet#15]
感谢你们杰出的工作！我希望能够将上面的图片通过Deblurring得到下面的这张图片
![train309](https://user-images.githubusercontent.com/58645050/165531473-1b9a0724-d0c0-4f67-b338-862830431466.jpg)
![train309](https://user-images.githubusercontent.com/58645050/165531427-6f63e1fa-d2ec-488a-84b7-ab0515d82768.jpg)
训练集是很多这种类型的图片，大小是1024*1024的，我应该对网络的哪些部分进行修改呀？

**Comment by mayorx** [comment]
Hi, renxiangdai 

单说网络结构的话， 建议是先在一个较小的模型上尝试一下， 比如
https://github.com/megvii-research/NAFNet/blob/main/options/train/GoPro/NAFNet-width32.yml#L45-L50
因为是灰度图， 所以可能需要额外添加一个参数 img_channel: 1 表示输入输出图片为1通道的。
此外完全可以根据实验结果随意调整这边encoder / decoder 的block分布

**Comment by renxiangdai** [comment]
感谢你的帮助!

我将encoder和decoder的block调整为：

  enc_blk_nums: [1, 1, 1, 1]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]




得到的结果很好，然而和Ground Truth相比还是有些模糊，上面的图是Ground Truth，下面的图是网络生成的
![377_STED](https://user-images.githubusercontent.com/58645050/165743648-7d3954b7-5b75-4a14-bbaf-53ad812cc5e8.jpg)
![377_NAF](https://user-images.githubusercontent.com/58645050/165743674-e788a463-ee0c-407c-9692-788a516e0c0e.jpg)
能不能给我一些调参的建议呀？

**Comment by mayorx** [comment]
Hi, renxiangdai

这个任务应该不是传统意义上的“去模糊”， 有点像去噪任务。
如果说调参的话， 最重要的就是学习率；另外可以看下训练iters的影响；其他的话，比如模型可以尝试加大（此时学习率可能也需要调整）
如果追求视觉效果上的sharp，可能可以尝试一些基于感知的方法， 比如perceptual loss/ GAN loss等等

**Comment by renxiangdai** [comment]
感谢你的帮助～
