### ISSUE TITLE
亲爱的作者，有个训练loss为负数的问题？

### ISSUE THREAD

**Issue by chenjiachengzzz** [megvii-research/NAFNet#19]
![image](https://user-images.githubusercontent.com/54382260/165960703-ffecc2c5-d09a-431a-8840-9feda08e9985.png)

**Comment by ZhH-17** [comment]
因为losses.py的psnr loss写错了，少个负号，所以是负的

**Comment by chenjiachengzzz** [comment]
> Hi, chenjiachengzzz,
> 
> Loss确实会是负数， 但我们认为这并不是一个“错误”或者“问题”，因为负的loss并不影响模型的优化过程。

嗯嗯，感谢大佬的耐心回复！

**Comment by chenjiachengzzz** [comment]
> 因为losses.py的psnr loss写错了，少个负号，所以是负的

嗯嗯，感谢大佬的耐心回复！
