### ISSUE TITLE
关于NAFNet-REDS-width64的Deblur问题

### ISSUE THREAD

**Issue by xiaohulihutu** [megvii-research/NAFNet#25]
作者您好，
我在测试demo的时候有的模糊照片处理的非常好，但是有照片会出现下面这种彩色马赛克的情况。请问您知道是什么问题吗
![ab2651213c8fafe52dec1156b2b4b59](https://user-images.githubusercontent.com/25570249/167824302-e828ca6b-b72a-4e60-a21f-4ca7de6cfa4c.png)

**Comment by mayorx** [comment]
xiaohulihutu, 您好，

我们猜测这可能是因为deblur的数据集的数据分布较为集中（街景，场景数量受限如REDS仅240个场景），其blur的分布和一些真实情景下的分布差异较大，而只见过非常受限数据分布的模型见到分布完全不一样的图片处理出现了问题。

我们在一个真实模糊数据集上（RHM-250) 简单测试了一下该模型， 大概有 0.3%的数据会有该问题([可视化结果下载链接](https://pan.baidu.com/s/1nuOadb7TOQC4yexGM_Jlpg?pwd=8gvg))，预估差异越大该问题发生的频率也会越高。一种缓解方法是，可以将TLSC的选项关掉（将NAFNetLocal 改为 NAFNet即可）此时在RHM-250测试集中该现象未被观测到。
此外，如我们在[NAFSSR](https://arxiv.org/pdf/2204.08714.pdf) (table 4.) 中讨论的，对模型增加一些限制（如droppath）可能可以对模型在out-distribution 的数据中的结果有所提升。
除了上述两个方法，我们观测到训练过程中让模型“见”到更多不同的数据可以有效缓解该问题。

**Comment by xiaohulihutu** [comment]
十分感谢。我尝试一下。如果有问题再问您。谢谢！

**Comment by songge25** [comment]
TLSC 替换为NAFnet似乎减少了这种问题，但是图像的清晰度也下降较多
