### ISSUE TITLE
NAFNet-error

### ISSUE THREAD

**Issue by 123456789-qwer** [megvii-research/NAFNet#26]
你好，这是非常棒的工作！
我在重新训练网络时遇到一些问题，在生成GoPro的crop的时候生成的文件夹里面crop的图片数量为0，这是什么原因？
感谢您的解答！

**Comment by mayorx** [comment]
Hi, @123456789-qwer,
您好，可否提供更加详细的信息？
[这段脚本](https://github.com/megvii-research/NAFNet/blob/main/scripts/data_preparation/gopro.py#L23-L35) 所做的事情是将 ./datasets/GoPro/train/input 和 ./datasets/GoPro/train/target 两个文件夹下的图片， 按照512x512的大小crop然后放在 ./datasets/GoPro/train/blur_crops ， ./datasets/GoPro/train/sharp_crops 两个目录下，最后[制作为lmdb格式](https://github.com/megvii-research/NAFNet/blob/main/scripts/data_preparation/gopro.py#L37) 
在运行脚本之前您可以先检查一下 ./datasets/GoPro/train/input  && ./datasets/GoPro/train/target  这两个目录下是否有对应的文件？
