### ISSUE TITLE
关于layernorm维度的问题

### ISSUE THREAD

**Issue by HLIG** [megvii-research/NAFNet#29]
大佬你好，感谢你们的开源。注意到你们NAFBlock中的layernorm(LN)模块，是在通道(C)维度上求的均值和方差，传统LN好像是在CHW维度上求的。想请教下，这两者是有较大的性能区别吗。

**Comment by mayorx** [comment]
HLIG，您好， 

从这波transformer应用到cv领域（带来LN替换BN），绝大部分的LN都是在C这个维度上的，如DETR，Swin，包括相关的ConvNeXt等工作。我们延续了这个设计，只不过自己实现了一版支持N C H W维度的LN，和上面提到的其他方法的LN是等效的。

**Comment by HLIG** [comment]
感谢大佬~

**Comment by LuletterSoul** [comment]
@HLIG  C维度上计算好像是BN吧，有大佬来澄清一下吗，看完仓库的LN实现有点懵。

**Comment by swift-n-brutal** [comment]
> @HLIG C维度上计算好像是BN吧，有大佬来澄清一下吗，看完仓库的LN实现有点懵。

不是BN，是类似Progressive GAN里的减均值的PixelNorm，再加通道维度的AffineTransform。
关于LayerNorm，pytorch官方给的[例子](https://pytorch.org/docs/stable/generated/torch.nn.LayerNorm.html?highlight=layernorm#torch.nn.LayerNorm)是`layer_norm = nn.LayerNorm([C, H, W])`，也就是每个样本的所有元素都用来归一化。但是SwinIR这类的写法是` nn.LayerNorm([C])`（默认channel_last），也就是每个位置上的C个通道值用来归一化。
（之前我也以为LayerNorm就是官方的版本，结果一直训不出来，原来套路这么多）
