### ISSUE TITLE
About droppath in NAFSSR

### ISSUE THREAD

**Issue by dslisleedh** [megvii-research/NAFNet#32]
Hi, Thank you for your great work. But i have question about implementation of droppath in NAFSSR.

Your droppath is quite different to timm/tfa's implementations. These 2 implementations drop samples in batch, but i think your implementation drops whole batch when training network. I wonder there's reason to this.

**Comment by mayorx** [comment]
Hi, dslisleedh,

We implement it in this way because it saves some time compared to the timm's implementation, as some of the blocks will be literally "dropped" and will not be counted in each training iteration.

**Comment by dslisleedh** [comment]
Ahhh i understand. Thank you

**Comment by mayorx** [comment]
It saved a lot of time when we participate in the NTIRE challenge : ).
