### ISSUE TITLE
About the pix_loss

### ISSUE THREAD

**Issue by b0ba11** [megvii-research/NAFNet#34]
Hi, thanks for your great work! I am training on DPDD dataset for restoring defocus images, and I get the the pix_loss as follows:
`2022-06-03 03:01:12,848 INFO: [NAFNe..][epoch:200, iter:  70,400, lr:(7.242e-04,)] [eta: 15:02:14, time (data): 0.399 (0.008)] l_pix: -2.8745e+01`
`2022-06-03 03:02:35,619 INFO: [NAFNe..][epoch:201, iter:  70,600, lr:(7.228e-04,)] [eta: 15:00:49, time (data): 0.403 (0.009)] l_pix: -2.9588e+01` 
`2022-06-03 03:03:57,277 INFO: [NAFNe..][epoch:202, iter:  70,800, lr:(7.214e-04,)] [eta: 14:59:20, time (data): 0.403 (0.009)] l_pix: -2.8007e+01` 
`2022-06-03 03:05:18,126 INFO: [NAFNe..][epoch:202, iter:  71,000, lr:(7.200e-04,)] [eta: 14:57:50, time (data): 0.402 (0.008)] l_pix: -2.7306e+01 `
I wonder if this value (l_pix) is normal or not, would you please share me your training log? Many thanks!

**Comment by mayorx** [comment]
Hi, b0ba11,
Hi, l_pix is normal, as we adopt the PSNR loss (-PSNR as loss function)
