### ISSUE TITLE
Random image as result of deblurring 

### ISSUE THREAD

**Issue by tianshuo** [megvii-research/NAFNet#38]
Running the following command `python3 basicsr/demo.py -opt  options/test/GoPro/NAFNet-width64.yml --input_path ./demo/noisy.png --output_path ./demo/denoise_img2.png`

Results in the following image
![denoise_img](https://user-images.githubusercontent.com/232424/176619104-be364090-fd54-4d5e-8c74-87657ead968e.png)

Using CPU instead of GPU on Macbook Pro, downloaded `NAFNet-GoPro-width64.pth` from baidupan, md5 is `7b7f519ce4203d701dc026ff0c3fd6e0`

**Comment by tianshuo** [comment]
My bad, used the denoising image as deblurring...

**Comment by AmmarMohanna** [comment]
Can you explain a bit about how you solved that issue?

I am trying to run NAFNet inference in a Docker image on a CPU, and getting a similar result to yours.
The same image works on the Colab demo and fails locally.

Thank you.
