### ISSUE TITLE
About JPEG artifact dataset (REDS)

### ISSUE THREAD

**Issue by four1000** [megvii-research/NAFNet#43]
想請問一下，你們的REDS with jpeg artifact這個資料集
是使用了多少壓縮率的jpeg參數(或是quality保留度)去做前處理呢?

**Comment by mayorx** [comment]
您好， 我们是直接使用 NTIRE21 ， Image deblurring challenge - track2 的设置， 
https://seungjunnah.github.io/Datasets/reds.html ，其中 “Blur + JPEG” 就是相关数据文件。

在[文章](https://openaccess.thecvf.com/content/CVPR2021W/NTIRE/papers/Nah_NTIRE_2021_Challenge_on_Image_Deblurring_CVPRW_2021_paper.pdf)中作者的原话为：

![截屏2022-07-05 下午2 03 53](https://user-images.githubusercontent.com/27191939/177260252-e402df7f-4064-4021-8fb9-8ea6be8fffa7.jpg) ， 
希望对您有帮助。

**Comment by four1000** [comment]
了解了 感謝您撥空回覆 謝謝~
