### ISSUE TITLE
pretrained plainnet and baselinenet

### ISSUE THREAD

**Issue by YouCaiJun98** [megvii-research/NAFNet#47]
Hello and congratulations on your ECCV22 acceptance!
I wonder if it's convenient for you to share the pretrained checkpoints of PlainNet and BaselineNet in your paper, many thanks :)

**Comment by mayorx** [comment]
Hi, YouCaiJun98,
Thanks! The Baseline pre-trained weights will be released (it may take some days), thanks for your advice!
We have no plan to release PlainNet yet.
