### ISSUE TITLE
GMAC results

### ISSUE THREAD

**Issue by Lucien1996** [megvii-research/NAFNet#51]
we use the NAFNet-main/basicsr/models/archs/NAFNet_arch.py to calculate GMAC under the configuration：
'''
width = 64 
enc_blks = [2, 2, 4, 8] 
middle_blk_num = 12 
dec_blks = [2, 2, 2, 2]
'''
the results：
'''
enc blks [2, 2, 4, 8] middle blk num 12 dec blks [2, 2, 2, 2] width 64
start .  1038.19140625
network ..  1485.99609375
end ..  12193.1953125
254.37 115.9
total ..  13120.3953125
'''
when we set width to 32:
'''
width = 32
enc_blks = [2, 2, 4, 8] 
middle_blk_num = 12 
dec_blks = [2, 2, 2, 2]
'''
the results：
'''
enc blks [2, 2, 4, 8] middle blk num 12 dec blks [2, 2, 2, 2] width 32
start .  1037.89453125
network ..  1154.34375
end ..  6870.11328125
64.9 29.1
total ..  7102.91328125
'''
In my understanding, the paper report in SIDD dataset（PSNR：40.30，SSIM：0.962，GMAC：65) adopt width=64.  Is this difference caused by my misunderstanding or the setting problem？

**Comment by mayorx** [comment]
Hi, Lucien1996,
Thanks for your attention to NAFNet. Following some related works, we report the GMACs with an input size of 256x256 in our paper. The GMAC computed in NAFNet-main/basicsr/models/archs/NAFNet_arch.py is for reference only, and it computes with an input size of [512x512](https://github.com/megvii-research/NAFNet/blob/main/basicsr/models/archs/NAFNet_arch.py#L222).

**Comment by Lucien1996** [comment]
I sincerely thank you for your reply！
