### ISSUE TITLE
请问有在超分任务上做过实验吗

### ISSUE THREAD

**Issue by KeyuLi** [megvii-research/NAFNet#54]
比较好奇作者或者其他人有在超分任务上做过相应实验吗

**Comment by mayorx** [comment]
KeyuLi, 您好，
感谢您对NAFNet的关注。 为了验证NAFNet在超分任务上的潜力， 我们参加了NTIRE22， 双目超分比赛并拿了冠军（在NAFNet基础上加了简单的双目融合模块提出[NAFSSR](https://arxiv.org/abs/2204.08714))。
欢迎在经典的超分任务上尝试（我们简单试了一下， 在计算量公平对比下应该不弱于现有SOTA如SwinIR）。

**Comment by KeyuLi** [comment]
好的，谢谢～
