### ISSUE TITLE
PSNR and SSIM

### ISSUE THREAD

**Issue by Lucien66** [megvii-research/NAFNet#61]
I have a question about how to calculate SSIM and PSNR value on SIDD_val dataset after running the test.py and obtaining the PNG file of the patch.

**Comment by mayorx** [comment]
Hi, Lucien66,
Sorry I am not sure about your question. Have you followed the instructions of "[test on SIDD dataset](https://github.com/megvii-research/NAFNet/blob/main/docs/SIDD.md#testing-on-sidd-dataset)" and  there are the hyper-parameters of the testing: https://github.com/megvii-research/NAFNet/blob/main/options/test/SIDD/NAFNet-width32.yml#L43-L55.
