### ISSUE TITLE
cannot import name 'create_dataloader' from 'basicsr.data' 

### ISSUE THREAD

**Issue by whzbzyll** [megvii-research/NAFNet#68]
![image](https://user-images.githubusercontent.com/93807594/189646444-0c33b232-f629-4082-a8bb-1576ec67f800.png)
![image](https://user-images.githubusercontent.com/93807594/189646566-d824e138-36ad-4e42-b803-89eea4e1311f.png)
Thank you for your contribution. We are having problems with create_dataloader not being imported successfully when training the dataset. We also found the same problem when testing with the colab test link you provided, and would appreciate your help.

**Comment by whzbzyll** [comment]
Resolved

**Comment by hs0817** [comment]
Hello, I also encountered the same problem, how do you solve it ?

**Comment by whzbzyll** [comment]
At first time forget to run the setup.py file and run this file to fix the problem. If the problem is not solved, you can try to change the file name of the library.

**Comment by hs0817** [comment]
Thank you

**Comment by COS-HSL** [comment]
> At first time forget to run the setup.py file and run this file to fix the problem. If the problem is not solved, you can try to change the file name of the library.

Hello, do you need to run the setup.py file successfully to solve this problem? I see no mention in the original author's reproduction process of running the setup.py file.
Thank you for your help.
