### ISSUE TITLE
Ablation Study: number of NAFBlocks

### ISSUE THREAD

**Issue by four1000** [megvii-research/NAFNet#7]
In your ablation study, you did the experiment of performance according to different number of  NAFBlocks.
I would like to know is this "number" for each en/decode layer's NAFBlock or just for some certain layer ?

**Comment by mayorx** [comment]
Hi, four1000,
Thanks for your attention to NAFNet.
This "number" indicates the total number of NAFBlocks, i.e. the sum of the number of NAFBlocks in the en/decode layers.
